# Copyright (C) 2022 SanCloud Ltd
# SPDX-License-Identifier: GPL-2.0-only

name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sancloudltd/iot-crossdev:dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure u-boot
        run: |
          . /opt/toolchain/setenv
          make sancloud_defconfig

      - name: Build u-boot
        run: |
          . /opt/toolchain/setenv
          make -j4 all
